= suricatta documentation
Andrey Antukh, <niwi@niwi.nz>
2.0.0
:toc: left
:!numbered:
:source-highlighter: pygments
:pygments-style: friendly
:sectlinks:


== Introduction

_suricatta_ is a high level sql toolkit for clojure (backed by fantastic
link:http://www.jooq.org/[jooq library])

It consists in four modules:

- *suricatta.core*: api for executing queries.
- *suricatta.dsl.alpha*: lightweight dsl for idiomatic and composable sql building.


=== Project Maturity

Since _suricatta_ is a young project there may be some API breakage.


=== Install

The simplest way to use _suricatta_ in a clojure project, is by including it in the
dependency vector on your *_project.clj_* file:

[source,clojure]
----
[funcool/suricatta "2.0.0"]
----

_Suricatta_ is only runs with *JDK >= 8* and *Clojure >= 1.5*


== SQL Execution

This section explains the usage of the sql execution part of the library.


=== Connecting to database

_suricatta_, unlike other database libraries, uses a concept of *context* instead
of *connection*. A **context** has the resposibility of jdbc connection resource
management, transaction isolation flags and sql rendering dialect.

You can create a **context** from:

- a datasource instance (connection pool).
- a valid jdbc url


==== Create Context from jdbc url

.Example creating context from dbspec.
[source, clojure]
----
(require '[suricatta.core :as sc])

(with-open [ctx (sc/context "h2:mem:")]
  (do-something-with ctx))
----


==== Create Context from DataSource.

DataSource is the preferd way to connect to the database in production enviroments
and is usually used to implement connection pools.

In our case we will use *hikaricp* as a datasource with a connection pool. Lets
start by adding hikari's dependency entry to your _deps.edn_:

[source, clojure]
----
hikari-cp/hikari-cp {:mvn/version "2.7.1"}
----

Now create the datasource instance:

[source, clojure]
----
(require '[hikari-cp.core :as hikari])

(def ^javax.sql.Datasource datasource 
  (hikari/make-datasource
    {:connection-timeout 30000
     :idle-timeout 600000
     :max-lifetime 1800000
     :minimum-idle 10
     :maximum-pool-size  10
     :adapter "postgresql"
     :username "username"
     :password "password"
     :database-name "database"
     :server-name "localhost"
     :port-number 5432}))
----

Now, having a datasource instace, you can use it like plain dbspec for creating
a context instance:

[source, clojure]
----
(with-open [ctx (sc/context datasource)]
  (do-something-with ctx))
----

You can found more information and documentation about hikari-cp
here: https://github.com/tomekw/hikari-cp


=== Executing queries

_suricatta_ has a clear separation between queries that can return a result, and
queries that can't.

.Example using `suricatta.core/execute` function.
[source, clojure]
----
(require '[suricatta.core :as sc])
(sc/execute ctx "CREATE TABLE foo")
----

The return value of `suricatta.core/execute` function depends on the query, but
in almost all cases it returns a number of affected rows.


=== Fetching results

Let see an example of how to execute a query and fetch results:

[source, clojure]
----
(require '[suricatta.core :as sc])
(sc/fetch ctx "select x from generate_series(1,3) as x")
;; => [{:x 1} {:x 2} {:x 3}]

(sc/fetch-one ctx "select x from generate_series(1,1) as x")
;; => {:x 1}
----

[NOTE]
====
_suricatta_ gives you the power of raw sql queries without
any restrictions (unlike jdbc). As a great example, _suricatta_ does
not have special syntax for queries with `RETURNING` clause:

[source, clojure]
----
(sc/fetch ctx "INSERT INTO foo (name) values ('bar') returning id")
;; => [{:id 27}]
----
====


=== Parametrized queries

Like _clojure.jdbc_ and _clojure.java.jdbc_, _suricatta_ has support for
parametrized queries in *sqlvec* format.

[source, clojure]
----
(sc/fetch ctx ["select id from books where age > ? limit 1" 100])
;; => [{:id 4232}]
----


=== Reusing query statement

The above technique can be quite useful when you want to reuse expensive database
resources.

[source, clojure]
----
(with-open [q (sc/query ctx ["select ?" 1])]
  (sc/fetch ctx q)  ;; Creates a statement
  (sc/fetch ctx q)) ;; Reuses the previous created statement
----


=== Transactions

The _suricatta_ library does not have support for low level transactions api,
instead of it, offers a lightweight abstraction over complex transaction api.

.Execute a query in a transaction block.
[source, clojure]
----
(sc/atomic-apply ctx (fn [ctx]
                       (sc/fetch ctx "select id, name from book for update")))
----

Additionally to `atomic-apply` high order functiom, _suricatta_ has a convenient
macro offering lightweight sugar sytax for atomic blocks:

.Execute a query in a transaction block using sugar syntax macro.
[source, clojure]
----
(sc/atomic ctx
  (sc/fetch ctx "select id, name from book for update"))
----

You can nest atomic usage as deep as you want, subtransactions are fully supported.

If an exception is raised inside atomic context the transaction will be aborted.
Also, in some circumstances, you probably want an explicit rollback, for which
the _suricatta_ library exposes a `suricatta.core/set-rollback!` function.

.Explicit rollback example
[source, clojure]
----
(sc/atomic ctx
  (sc/execute ctx "update table1 set f1 = 1")
  (sc/set-rollback! ctx))
----

The `set-rollback!` function only marks the current transaction for rollback. It
does not abort the execution, and it is aware of subtransactions. If it is used
in a subtransaction, only the subtransaction will be marked for rollback, not
the entire transaction.


=== Lazy result fetching

The _suricatta_ library also comes with lazy fetching support. When lazy fetching
support is enabled, instead of fetching all results in memory, suricatta will
fetch results in small groups, allowing lower memory usage.

Lazy fetching has a few quirks:

- In some databases, like _PostgreSQL_, it requires the entire fetch to occur in
  one transaction because it uses  server side cursors.
- Lazy fetching requires explicit resource management, because a connection and
  an internal resultset must be mantained open until fetching is finished.

Using lazy fetch is realy easy, because suricatta exposes it as a simple lazy
sequence. Let's see one example:

.Example executing large query and fetching elemens in groups of 10.
[source, clojure]
----
(def sql "SELECT x FROM generate_series(1, 10000)")

(sc/atomic ctx
  (with-open [cursor (sc/fetch-lazy ctx sql {:fetch-size 10})]
    (doseq [item (sc/cursor->seq cursor)]
      (println item))))

;; This should print something similar to:
;; {:x 1}
;; {:x 2}
;; ...
----

The third parameter  of `sc/fetch-lazy` function is  the optional. The
default fetch size is `128`.


=== Custom types

If you want to use suricatta with a database that exposes
non-standard/complex types, suricatta provides an easy path for
extending it. That consists in two protocols, one for converting user
defined types to jooq/jdbc compatible types, and other for backwards
conversion.

.Example adapting clojure persistent map interface to postgresql json file.
[source, clojure]
----
(require '[suricatta.proto :as proto]
         '[suricatta.impl :as impl]
         '[cheshire.core :as json])

(import 'org.postgresql.util.PGobject)

(extend-protocol proto/IParam
  clojure.lang.IPersistentMap
  (-param [self ctx]
    (let [qp (json/encode (.-data self))]
      (impl/sql->param "{0}::json" qp))))
----

The `-param` function is responsible of generate the appropiate sql
part for this field.

Now let see the backward conversion example:

[source, clojure]
----
(extend-protocol proto/ISQLType
  PGobject
  (-convert [self]
    (let [type (.getType self)]
      (condp = type
        "json" (json/decode (.getValue self) true)))))
----

Having defined the two way conversions, you can pass the clojure hash-map as a
value to the query and it is automatically converted.

.Insert and query example using postgresql json fields.
[source, clojure]
----
;; Create table
(sc/execute ctx "create table t1 (k json)")

;; Insert a json value
(sc/execute ctx ["insert into t1 (k) values (?)" {:foo 1}])

;; Query a table with json value
(sc/fetch ctx ["select * from t1"])
;; => [{:k {:foo 1}}]
----


== SQL Building and Formatting

TBD

Since version 2.0.0, the complex sql composition functions based on
jooq are eliminated (buggy and complex code that uses api mostly
defined for java). There are `suricatta.dsl.alpha` namespace that
contains a work in progress of the new approach.

If you want play with that look tests code to see how it works.


== FAQ

=== Why I should use suricatta instead of next.jdbc or java.jdbc?

Unlike any jdbc library, _suricatta_ works at a slightly higher level. It hides a
lot of idiosyncrasies of jdbc under a much *simpler, cleaner and less error prone
api*, with better resource management.


=== Why another dsl? Is it just yet another dsl?

First _suricatta_ is not a dsl library, it's a sql toolkit, and one part of the
toolkit is a dsl.

Secondly, _suricatta_'s dsl's don't intends to be a sql abstraction. The real
purpose of _suricatta_'s dsl is make SQL composable while still allowing use all or
almost all vendor specific sql constructions.


=== What are some suricatta use cases?

The _suricatta_ library is very flexible and it can be used in very different ways:

- You can build queries with _suricatta_ and execute them with _next.jdbc_.
- You can use _suricatta_ for executing queries with string-based sql.
- You can combine the _suricatta_ library with _next.jdbc_.
- And obviously, you can forget jdbc and use _suricatta_ for both purposes, building
  and/or executing queries.


=== Is it a korma-clone?

Nope, it's not korma clone, because it works very different, and it has a different
philosophy.

_suricatta_ has cleaner differentiation between dsl and query execution/fetching.
It doesn't intend to be a replacement of Korma, it intends be a replacement to raw
jdbc access to the database.


=== Is a JOOQ comercial license requried?

Not, _suricatta_ works and is tested with the opensource (Apache 2.0 licensed)
version of JOOQ.

I have plans to make _suricatta_ work with enterprise version of JOOQ for users
that want to use "enterprise" databases in the future. In any case, that will not
affect the open source version.


=== Can I store safely queries builded by DSL in a var, they are immutable?

Yes. Unlike JOOQ DSL interface which has a mutable api, _suricatta_ exposes an
immutable api for building queries.

Queries built with _suricatta_ can be safely shared through different threads.


== Developers Guide

=== Philosophy

The five most important rules are:

- Beautiful is better than ugly.
- Explicit is better than implicit.
- Simple is better than complex.
- Complex is better than complicated.
- Readability counts.

All contributions to _suricatta_ should keep these important rules in mind.


=== Contributing

Unlike Clojure and other Clojure contributed libraries _suricatta_ does not have many
restrictions for contributions. Just open an issue or pull request.


=== Source Code

_suricatta_ is open source and can be found on
link:https://github.com/funcool/suricatta[github].

You can clone the public repository with this command:

[source,text]
----
git clone https://github.com/funcool/suricatta
----


=== Run tests

[source, text]
----
clojure -Adev:test
----

=== License

_suricatta_ is licensed under BSD (2-Clause) license:

----
Copyright (c) 2014-2019 Andrey Antukh <niwi@niwi.nz>

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
----
